### ISSUE TITLE
InverseGravity

### ISSUE THREAD

**Issue by wdhif** [SupinfoGameDev/FuckNewton#1]
Crée le script InverseGravity en C#

Script qui va inversé la gravité du jeu à la pression d'une touche.

**Comment by wdhif** [comment]
Ok ça avance, le perso se "retourne" quand la gravité change mais il en "remonte" pas encore :(

**Comment by massinissa-boutrig** [comment]
salut wassim,

Je vois dans notre projet LAB deux scripts qui s’appellent “Camera2Dfollow” et “CameraFollow” c’est normal?

massi

De : Wassim Dhif
Envoyé : ‎mardi‎ ‎15‎ ‎avril‎ ‎2014 ‎12‎:‎22
À : wdhif/FuckNewton

Ok ça avance, le perso se "retourne" quand la gravité change mais il en "remonte" pas encore :(

**Comment by wdhif** [comment]
Oui c'est normale, mais ne les modifie pas, fait le tien et nom le
CamFollow car CameraFollow et déjà pris

Je te montrerais au pire demain au labo

Le 15 avril 2014 23:12, massinissa-boutrig notifications@github.com a
écrit :

**Comment by massinissa-boutrig** [comment]
Je ne serai surement pas là demain au labo car je suis chez mes parents à plus 170km

désolé

De : Wassim Dhif
Envoyé : ‎mardi‎ ‎15‎ ‎avril‎ ‎2014 ‎23‎:‎14
À : wdhif/FuckNewton
Cc : Massinissa Boutrig

Oui c'est normale, mais ne les modifie pas, fait le tien et nom le 
CamFollow car CameraFollow et déjà pris 

Je te montrerais au pire demain au labo 

Le 15 avril 2014 23:12, massinissa-boutrig notifications@github.com a 
écrit :

**Comment by wdhif** [comment]
Pas de soucis, on verra ça à la rentré ^^

Le 15 avril 2014 23:22, massinissa-boutrig notifications@github.com a
écrit :

**Comment by wdhif** [comment]
A qui veut reprendre, je galère

**Comment by wdhif** [comment]
http://answers.unity3d.com/questions/59424/changing-gravity-at-the-click-of-a-button.html#

**Comment by massinissa-boutrig** [comment]
Salut wassim, j’ai fait  le script de FollowCamera, j’ai peurs de le github et de raser ce qui à été fait, je te l’envoie pour que tu puisse le voir et le gither
﻿using UnityEngine;
using System.Collections;

public class FollowCamera : MonoBehaviour {

```
public float positionX;

// Use this for initialization
void Start () {
    positionX = transform.position.x;   
}

// Update is called once per frame
void Update () {

    // Demplacement à gauche
    if((Input.GetKey(KeyCode.LeftArrow)))
    {
        positionX -= camera_velocity*Time.deltaTime;
        transform.position = new Vector3(posX,0,0);         
    }

    //Deplacement à droite
    if((Input.GetKey(KeyCode.RightArrow)))
    {
        positionX += camera_velocity*Time.deltaTime;
        transform.position = new Vector3(positionX,0,0);
    }

        }
```

}

**Comment by ghost** [comment]
L'inverseGravité est pratiquement fini. Il reste juste le bug du perso qui marche à l'envers lorsqu'il est en haut. Et je pensais modifier le saut du personnage. Peux-tu m'indiquer où ce situe le scripte pour ça ?
